---
title: "Introduction"
editor_options: 
  chunk_output_type: console
bibliography: paper1.bib
link-citations: true
csl: entomological-society-of-america-2.csl
suppress-bibliography: true
---

Ecologists and farmers frequently hold divergent views regarding the importance of natural habitats within agricultural landscapes, a distinction often overlooked in ecological and conservation discourse [@Tscharntke2016]. While ecologists recognize the role of natural habitats such as field border vegetation in supporting biodiversity and providing potential ecosystem services like biological pest control, many farmers perceive these semi-arid habitat remnants as occupying valuable cropland or even as sources of pests. As such, documenting how pest and natural enemy populations interact with agricultural landscapes alongside semi-natural habitat buffers on the crop periphery is important in determining the degree of the services or disservices provided. 

Numerous polyphagous insect herbivores and their natural enemies rely on a variety of resources found across diverse habitat types within their environment. Depending upon the quality of the resource, different habitat types can serve as sources for increased pest or natural enemy populations. Similarly, these habitat types can serve as sinks that decrease populations [@Kennedy2000]. Altering the presence of these resources can have impacts on pest or natural enemy populations and can alter the ecology between the examined species. For example, diversifying the edge cropping of organic *Brassica* using fava beans, fennel, and marigolds results in a diversity in beneficial arthropod communities that help reduce phytophagous herbivory [@DeMorais2023]. 

Understanding the ways in which landscape habitat diversity impacts the ecological relationship between pest and enemy is crucial for effectively managing pest species in large scale cropping systems. Similarly, understanding how herbivore plant-hosts act as reservoirs for pests or beneficial natural enemies can potentially play a role in stabilizing year-over-year agricultural impact from these pests [@Cano2022]. 

The wheat stem sawfly (WSS), Hymenoptera *Cephus cinctus* Norton, is a grass-mining sawfly native to North America [@Criddle1922; Ainslie1929; @Wallace1966; @Lesieur2016]. Originally adept at utilizing wild grass hosts, the species became a major pest to cultivated cereals as this resource became more prevalent following European settlement, becoming a notable pest of winter wheat in 1990 in Montana [@Morrill1996], and more recently in Colorado [@Cockrell2021]. Climate warming has the potential to further expand the range of this pest both northward and southward [@Olfert2019; @Weaver2023]. Adult female WSS use their saw-like ovipositor to lay their eggs in the lumen of stems, where the eggs hatch, leading to larval feeding of parenchyma tissue [Roemhild1954; @Holmes1956]. Economic damage manifests in the form of both kernel weight reduction caused by tissue damage [@Beres2011a; Delaney2010] and stem toppling due to late-season larval girdling [@Holmes1960; @Nansen2005a; @McCullough2020]. 
  
Several parasitoid or predatory species attack *C. cinctus* within wild grass hosts [@Davis1955; @Morrill1998, @Morrill2001], however, two species, *Bracon cephis* (Gahan) and *Bracon lissogaster* Muesebeck (Hymenoptera: Braconidae), have been observed targeting WSS within cultivated cereals [@Nelson1953; @Morrill1998; @Runyon2001a; @Runyon2001b]. These two host-specific ectoparasitoids are native to North America. Both parasitoids are bivoltine, with the first generation present in Montana from late-June to late-July, while the second generation is active from mid-July to September [@Gahan1918; @Somsen1956; @Davis2013]. Adult female *B. cephi* and *B. lissogaster* inject a paralytic toxin into a *C. cinctus* larvae within the host stem, paralyzing the host larvae, and depositing from a single (*B. cephi*) to 1-3 (*B. lissogaster*) eggs. *B. cephi* and *B. lissogaster* have been shown to provide biological control via irreplaceable mortality of *C. cinctus* populations [@Buteler2015; @Peterson2011] and can significantly reduce *C. cinctus* damage and impact on crop yields [@Buteler2008; @Adhikari2019; @Bekkerman2018; @Rand2020]. While *C. cinctus* has a wide range of viable host plants, including native and non-native grasses and cultivated row-crops such as wheat (*Triticum aestivum L.*) and barley (*Hordeum vulgare*) [@Wallace1966; @Cockrell2017; @Achhami2020], infestation levels can vary widely across hosts. Previous research has shown preference for host plants with larger stem diameter [@Ainslie1920; @Buteler2009; @Bhandari2020]. 

Recent research has shown natural non-cultivated grasses such as *Agropyron cristatum*, *Bromus techtorum*, *Bromus inermis*, *Elymus trachycaulus*, and *Thinopyrum intermedium* host *C. cinctus* and most also host Bracon spp. parasitoids quite well [@Mendoza2006; @Peirce2021; @Rand2024]. We find investigating *B. inermis* holds the most potential, as it has been shown to be a quality initially-accepted host for *C. cinctus* oviposition while also leading to high larval mortality later on [@Seamans1928; @Farstad1945]. However, there is a lack of detailed relating to the total infestation, cutting, and parasitism within *B. inermis* at multiple time points throughout the growing season. Quantitative assessment of potential 'reservoir' characteristics and local spatial information could prove useful in fully understanding the ecological impacts of maintaining *B. inermis* along roadways and within coulees.  

Smooth brome (*Bromus inermis* Leyss) is a Eurasian cool-season rhizomatous grass introduced to the United States in 1884 [@Bolwahn2011].*B. inermis* was originally thought of as potentially useful as a trap crop in order to combat the growing WSS problem with cultural control practices [@Criddle1922; @Seamans1928; @Farstad1945; @Beres2011a]. Due to its low agricultural value, and propensity to form monocultures and out compete many native grasses, *B. inermis* is categorized as invasive in some habitats [@Carlson1985; @Willson2000; @Dillemuth2008]. However, *B. inermis* still holds considerable ecological and potential economic value due to its late senescence and WSS antibiosis properties [@Otfinowski2006; @Rand2024].

Montana's golden triangle, an area of central and northern Montana with intense cereal grain production, is prone to drought and burning via wildfire [@Wilson1923; @Adhikari2019]. As both *C. cinctus* and its host-specific parasitoids are relatively restricted in their annual mobility [@Weaver2005], environmental extremes can have broad impacts on both local pest and natural enemy populations. As with many predator-prey interactions, the *C. cinctus* and parasitoid populations fluctuate, with crashes and spikes experienced in close succession and through ineteraction with drought [@Holmes1963; @Holmes1982]. Similar examples of these classical population dynamics patterns can be found in wolves and moose on Isle Royale [@Peterson1999], and Coccinellidae and aphids [@Evans1999], among others. 

We examined historical weather data from two field locations (10 sites overall) in central and northern Montana. We used this data to understand how changes in global climate trends may be impacting *C. cinctus*, *B. cephi* and *B. lissogaster* interact with *B. inermis* populations. In addition we analyzed normalized difference vegetative index (NDVI) at our field sites to understand how *B. inermis* senescence patterns compare to adjacent cultivated wheat fields. 

In this study, we explored the ecological patterns between Montana populations of *C. cinctus* and its associated braconid parasitoids in relation to *B. inermis* host sites. Our goal, was 1) to understand the degree to which *C. cinctus* infested *B. inermis* stems in relation to neighboring cereal crops, and 2) the way in which braconid parasitoids utilized WSS hosts available within *B. inermis* stems. To do so, we conducted two separate studies. In our first study, we conducted controlled *C. cinctus* infestation of *B. inermis* to understand the relative infestation and cutting rate of *C. cinctus* within the *B. inermis* stems in the absence of parasitoids. The second study examined rates of cutting and parasitism in wheat crops and their surroundings at field sites in central and northern Montana. 

Using these studies, we addressed three questions, 1) what is the total *C. cinctus*-caused stem cutting heading into overwinter - and thus the source rate, of the subsequent *C. cinctus* population in *B. inermis*? 2) can *C. cinctus* larvae within *B. inermis* serve as critical second generation hosts for *B. cephi* and *B. lissogaster*? and 3) how do annual *C. cinctus* and parasitoid populations in *B. inermis* compare with those in the adjacent cultivated wheat fields?


