---
title: "Materials and Methods"
editor_options: 
  chunk_output_type: console
bibliography: paper1.bib
link-citations: true
csl: entomological-society-of-america-2.csl
# suppress-bibliography: true
---

## Controlled *C. cinctus* infestation of *B. inermis* {.unnumbered}

*Insects and Cages.* Assessment of *C. cinctus* infestation and mortality within *B. inermis* were assessed using a 34 x 60 ft plot at the Arthur H. Post Agronomy Farm (43°38'19.39"N, 116°14'28.86"W), an experimental farm of Montana State University in Bozeman, MT. There is a negligible population of *C. cinctus* and associated parasitoids at this location. Experimental cages  were built using 1-inch PVC piping with the netting made using 530$\mu$ Amber Lumite Screen (BioQuip$^\circledR$ Products, LLC). Twelve cages were built to dimensions of 6ft x 3ft x 3ft (L x W x H) with cage locations selected randomly based on the space available within the plot and arranged in sets of three.

Wheat stem stubble was collected in Three Forks, MT, USA (43°38'19.39"N, 116°14'28.86"W) from fields that experienced high levels of *C. cinctus* infestation and cutting the year prior, as previously described [@Hager2024]. Cut stubble, which contained *C. cinctus* larvae in diapause, were kept refrigerated between -2°C and 3°C for \>100 days as required to complete obligatory larval diapause. As needed, stubs were removed from refrigeration and kept at 22-27°C for 4-5 weeks inside of 100 oz GladWare® storage containers (Glad®, Oakland, California USA). Once *B. inermis* stems reached six inches tall, stub containers with emerging sawflies were added to cages to mimic sawfly infestation pressure. Sawfly quantity treatments were as follows: high (600 stubs), low (200 stubs), and control (0 stubs).

*Data Collection.* In late August, *B. inermis* stems were collected from each cage. Each stem was dissected using X-Acto® knives to collect data on infestation, dead larvae and live larvae, as well as very rare parasitism events, for each internode.

## Montana Field Survey {.unnumbered}

*Weather data and NDVI* Field sites were chosen across two counties, Choteau and Judith Basin, within the 'Golden Triangle' of Montana, United States [fig. 1](#figure1), areas that consistently experience high *C. cinctus* pressure. We assessed the medium- and long-term temperature and precipitation trends of our field sites using weather data from the National Oceanic and Atmospheric Administration (NOAA, Silver Spring, MA, USA). Data for each field site was averaged from three of the closest weather stations to that location. 

To better understand how precipitation patterns vary throughout the growing season, we looked at local daily precipitation totals from weather stations at our sampling sites in Big Sandy and Moccasin, MT. Data was pulled online from historical WeatherUnderground weather station data [@WeatherUnderground]. Precipitation readings were broken into two categories - dates before July 15 and after September 15, as well as between July 15 and September 15. These dates were chosen based on typical wheat harvest and historical periods of known *Bracon* spp activity. In the 'Golden Triangle', typical spring wheat harvest takes place in mid-July on average [@Wilson1923; @Zhu2021].

We used the normalized difference vegetation index (NDVI) to compare the relative greening throughout the growing season between wheat fields and adjacent *B. inermis* ([fig. 2](#figure2)). NDVI is typically used to assess vegetation health and density, and is calculated from the visible and near-infrared light reflected by vegetation [@Pettorelli2005]. NDVI data measurements were directly downloaded using Google Earth Engine (Google Inc. 2023, Mountain View, CA, USA).

*Stem collection and processing.* We conducted a field survey to assess *C. cinctus* infestation, larval mortality, and *B. cephi* and *B. lissogaster* prevalence within *B. inermis* and adjacent wheat fields. Samples were collected from wheat fields and adjacent *B. inermis* in early July and late August in 2022, and 2023 from sites in Big Sandy and Moccasin MT, USA. Sampling sites were set up as 100$m^2$ polygons along the edge of adjoining wheat fields. Four collection squares of 1ft x 1ft were randomly selected within each polygon during both collection events each year. All stems within each 1 x 1 ft square were collected using a shovel to remove both stem and root material. Wheat stems were collected at distances of 5 and 20 meters from the edge of the field. Samples were collected in 4 rows at 10 meters apart. 2 samples were collected in each row at distances of 5 and 20 meters. 1 ft samples were collected at each point.

Wheat and *B. inermis* stems were then returned to Montana State University, Bozeman, Montana and stored in a 10°C cold, humid storage until dissection. Stems were dissected in the same manner as samples from our controlled experiment. We recorded presence or absence of *C. cinctus* larval infestation, live eggs, dead eggs, dead larvae, live larvae and parasitism, in addition to stem cutting. Sawfly larvae were identified based on descriptions in Criddle (1915) and Wallace and McNeal (1996).

To better understand the densities of host *C. cinctus* and the *Bracon* spp. within the wheat and adjacent *B. inermis* at each sampling site, we converted our units to the ratio of parasitoids to surviving hosts stem per unit area. Densities of stems are different when considering semi-natural, long-standing stands of *B. inermis* and the adjacent cultivated wheat or barley. 

## Statistical Analysis {.unnumbered}

All statistical analyses were done in R [@R2024] using R Studio (version 4.3.2). Data was plotted using R package 'ggplot' (version 3.4.4) [@ggplot]. We analyzed long- and short-term weather trends using linear modeling and the 'lm' command. Weather data was analyzed using either average yearly precipitation (inches) or average yearly temperature (°C) as the response variable and year as the predictor. Similar to our weather data analysis, NDVI data was linear modeled to discern differences in NDVI measurements over time. 

We used generalized linear mixed models with binomial errors (logit link) fit using bound optimization by quadratic approximation, with a maximum of 200,000 iterations, were run in the *lme4* package in R [@lme4] to examine the effects of location and year (fixed effects) on each of the three response variables: proportion of stems infested, proportion of stems cut, and proportion of stems parasitized by *Bracon* spp. 
