---
title: "Discussion"
editor_options: 
  chunk_output_type: console
bibliography: paper1.bib
link-citations: true
csl: entomological-society-of-america-2.csl
suppress-bibliography: true
---

## Controlled Infestation {.unnumbered}  

Assessment of *C. cicntus* infestation and larval mortality within *B. inermis* from our controlled infestation survey showed high levels of infestation coupled with high larval mortality prior to overwintering diapause.  Even in cases of greater infestation (70%+), larval survival to cutting topped out around around 15%, pointing towards the capacity of *B. inermis'* to serve as a quality sink for WSS larvae. These results confirm the assertions by Criddle (1992) and Seamans (1928) that *B. inermis* could serve as a quality WSS trap crop. In addition to high levels of larval mortality, stem dissection indicated that a large number of stems had over four internodes burrowed through by WSS larvae. Larval movement through stems can be quick in the case of susceptible cultivated cereal grains [@Criddle1923]. However, *B. inermis*, given its presumed antibiosis properties and slow late-season senescence, leads to slower larval development and thus less movement through the stem. 

Our results build upon other studies that have reported high WSS larval mortality in *B. inermis* prior to overwintering [@Shanower2004; @Mendoza2006; @Buteler2008]. Of the infested stems, a significant proportion (2022: 57.1%, 2023: 62.3%, [Fig. 2](#fig2)) exhibited larval damage in four or more internodes. While the timing of stem collection and dissection in October did not allow for precise measurement of living larvae, we can assert that stems with at least four burrowed internodes would likely contain large, living larvae, and thus viable potential parasitoid hosts in late July and August of the same year. Additionally, we found several *B. inermis* stems with living larvae during our October dissections; these larvae may have been unable to cut stems at this late date.


### Weather and NDVI {.unnumbered}
Precipitation and temperature data from our sampling sites underscores the importance of continuing to monitor and conserve areas of semi-natural grassland. Our 50-year trend analysis aligns with Pederson et al (2009), indicating that the dry-land agricultural environments found in central and northern Montana are likely to become hotter and dryer on average. Over the past fifty years in Big Sandy, MT, precipitation has decreased by an average of 0.05 inches per year while temperatures have increased by an average of 0.03°C per year. If the trend continues, by 2050, the area could recieve an inch less rainfall and temperatures 0.75°C warmer annually. 

Both average precipitation and temperature varies widely between years as both Moccasin and Big Sandy, MT, routinely experience droughts and periods of relative high rainfall [@WeatherUnderground; @Pederson2009]. Shown in our five-year analysis, precipitation significantly decreases during the period after wheat harvest, July 15 - September 15, a period when second generation *Bracon* spp adults are searching for WSS larval hosts [@Nelson1953; Somsen1956]. Mid-season senescence of many WSS host plants can then leave *Bracon* parasitoids with limited host resources for perpetuating the population. Consequently, prolonged drought, like seen in 2021 in Big Sandy, MT, can cause a dearth of green host plants in these semi-arid environments that can be problematic for second generation adult parasitoids. 

Given this context, our analysis of NDVI at our sampling sites revealed that *B. inermis* is particularly capable of sustaining late-season greening. This continued greening may provide crucial resources for *Bracon* spp. parasitoids during years of drought or crop failure. In these buffer zones, parasitoids may be able to locate WSS larvae in sufficient numbers to prevent the large population crashes that can lead substantial, localized increases in WSS populations and subsequent heavy crop damage [@Holmes1963; @Holmes1982]. In addition, annual changes in temperature and precipitation could have significant impacts on the timing of crop production and harvest [@Zhu2021], leading to additional challenges for second generation *Bracon* spp adults. 


### Montana Field Site Survey {.unnumbered}

Previous research has shown *B. inermis* to be a quality host of both WSS and *Bracon* spp parasitoids [@Criddle1922; @Peirce2021; @Rand2024], but little data is available on the season fluctuation of both WSS time frames and *Bracon* spp utilization. Because we collected stem samples twice during the growing season, we were able to elucidate both host and parasitoid potential. 

Our results showed that parasitoid presence increase significantly at all sites between pre- and post-harvest collections ([Supp. Fig. 2](#supp2)). Given the collection methods, fall collection parasitism was inherently reflects a combination of both pre-harvest and post-harvest parasitoid activity. While our methods do not allow us to determine *Bracon* spp. preference for host stems from our results, they indicate that parasitoids may utilize infested *B. inermis* stems to a lesser degree pre-harvest compared to post-harvest, when WSS is no longer available within the adjacent wheat stems. Concurrently, we observed a high number of stems exhibiting four or more internodes of visible WSS damage, suggesting prolonged larval presence within *B. inermis* stems. Specifically, in Big Sandy (39.5%) and Moccasin (53.1%), stems that exhibited four or more nodes burrowed indicate that WSS larvae may remain available within *B. inermis* stems past wheat harvest, when availability is otherwise limited. This is particularly important in years of drought or increased temperatures, where wheat senescence and harvest may occur earlier in the summer. 

We utilized parasitism-to-cut-stem ratios to understand the relative impact of *B. inermis* host sources on overall field parasitism. Simply assessing the overall number of insects can potentially diminish the apparent importance of *B. inermis*, as per square meter stem counts in cultivated wheat are denser than *B. inermis* counts in semi-natural environments such as along roadsides. Our findings showed significantly greater ratios of parasitized stems to cut stems within *B. inermis* compared to adjacent wheat fields ([Fig. 8](#fig8)). This indicates that field-edge areas containing *B. inermis* provide a greater parasitoid source potential, per square meter, than adjacent cultivated fields. These results emphasize the significance of accounting for habitat diversity and ecological buffers to sustain parasitoid populations over successive years and highlight to crucial role of edge-row areas in maximizing parasitoid effectiveness in minimizing WSS damage.

Overall, this work suggests that *B. inermis* has the potential to play an important role in WSS damage mitigation and *Bracon* spp parasitoids. *B. inermis* exhibited low levels of WSS stem cutting while remaining a viable host for second-generation *Bracon* spp. parasitoids. Assessing the comparative abundance of WSS and its associated parasitoids within *B. inermis* and adjacent cultivated cereal hosts is an important initial step in evaluating whether semi-natural road-side environments serve as sink or source origins of the pest and its beneficial natural adversaries infiltrating agricultural crops. Further research is needed to understand the mechanisms behind *B. inermis's* dual ability to both slow larval development without causing early-instar mortality and prevent high WSS stem cutting typically seen in native grasses and cultivated cereals.  



\newpage